version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/nomikai-app
    ports:
      - "3000:3000"
    depends_on:
      - db